### ISSUE TITLE
Search results (on TEST) return missing language for both languages

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/dbs-back#152] opened 2017-04-20 09:09 UTC
### Overview
* Search results in English show an item that exists only in Hebrew, but while clicking it returns a 403.
* The same occurs in Hebrew, and for the same item, so the same item in both languages appears as available only in the other language.
* This seems to be happening **only on the TEST environment**, these items don't seem to exists on LIVE.

### Example
<img width="329" alt="screen shot 2017-04-20 at 11 24 34" src="https://cloud.githubusercontent.com/assets/20017334/25222684/cb901910-25c1-11e7-8d7c-741971c6e9ad.png">
<img width="326" alt="screen shot 2017-04-20 at 11 24 44" src="https://cloud.githubusercontent.com/assets/20017334/25222683/cb8b632a-25c1-11e7-9090-cb9fbda3eb2a.png">

**Comment by Libisch** [comment] 2017-04-23 08:12
@OriHoch

**Comment by OriHoch** [comment] 2017-04-24 08:01
http://test.dbs.bh.org.il/search?q=wasilkow

**Comment by OriHoch** [comment] 2017-04-24 08:08
the problem is probably due to sync of persons taking too long, and places collection is after it - so places are not updated until persons sync is done..

I'll change the order of collections so that persons is updated last

**Comment by OriHoch** [comment] 2017-04-24 08:17
actually, it's already the last one.. 

I ran update manually on that item only and it worked - removed it from elasticsearch

going to run ensure_required_metadata again

**Comment by OriHoch** [comment] 2017-04-24 12:41
there was a problem with logic of which items to show

fixed in [latest draft release](https://github.com/Beit-Hatfutsot/dbs-back/releases)

I re-ran the ensure_required_metadata script to update all places - looks ok now

**Closed by OriHoch** 2017-04-24 12:41 UTC
Labels: bug
