### ISSUE TITLE
Missing Items/403 after running "ensure_meta_data.py"

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/dbs-back#153] opened 2017-04-24 08:15 UTC
Results show unavailable items, getting 403:

**Example**
"BIELSK" in [search results for "poland" in "places"](http://test.dbs.bh.org.il/search?q=poland&collection=places):

[<img width="333" alt="screen shot 2017-04-24 at 11 02 05" src="https://cloud.githubusercontent.com/assets/20017334/25327831/47c34b50-28de-11e7-8409-79873d04d48e.png">](http://test.dbs.bh.org.il/place/bielsk)

returns 403.

**Related issue:** [#152](https://github.com/Beit-Hatfutsot/dbs-back/issues/152) Search results (on TEST) return missing language for both languages

**Next step:** #154

**Comment by OriHoch** [comment] 2017-04-24 08:26
http://devapi.dbs.bh.org.il/v1/search?collection=places&from_=0&q=bielsk
```js
{
LocationInMuseum: null,
Pictures: [
{
PictureId: "1AEF2108-2392-4523-9400-023EBC251574",
IsPreview: "0"
},
{
PictureId: "5EAB2058-31DD-4014-8280-526FFD0C1B37",
IsPreview: "1"
},
{
PictureId: "670B16E9-B6D4-46CB-ABD7-788E0CB94A3B",
IsPreview: "0"
},
{
PictureId: "2695D6E9-FD45-4BE9-9E07-BF290C116B82",
IsPreview: "0"
},
{
PictureId: "6723F315-ED8F-4511-8DB7-D627029E5BB7",
IsPreview: "0"
},
{
PictureId: "974D7669-2A1E-4BD2-9E38-EFBC3A18CDF3",
IsPreview: "0"
}
],
PictureUnitsIds: "135828|12708|126285|136133|5080|48111|",
UpdateDate: "2015-08-06T11:54:00",
OldUnitId: "HB000417.HTM-EB000037.HTM",
UpdateUser: "***** ****** ",
PrevPictureFileNames: "AR2005-18-1.jpg|01223500.JPG|1-5a.jpg|AR2005-18-13.jpg|00458700.JPG|03617600.JPG|",
PrevPicturePaths: "Photos\1aef2108-2392-4523-9400-023ebc251574.jpg|Photos\00000613.scn\01223500.JPG|Photos\670b16e9-b6d4-46cb-abd7-788e0cb94a3b.jpg|Photos\2695d6e9-fd45-4be9-9e07-bf290c116b82.jpg|Photos\00000438.scn\00458700.JPG|Photos\00001269.scn\03617600.JPG|",
PlaceTypeCode: 2,
TS: "00000000003f983a",
PlaceTypeDesc: {
En: "Town",
He: "עיירה"
},
UnitType: 5,
UnitTypeDesc: "Place",
EditorRemarks: "hasavot from Places ",
DisplayStatusDesc: "Museum only",
RightsDesc: "Full",
Bibiliography: {
En: null,
He: "אנציקלופדיה יודאיקה"
},
UnitText1: {
En: "english text"
},
UnitText2: {
En: null,
He: null
},
UnitPlaces: [ ],
main_image_url: "https://storage.googleapis.com/bhs-flat-pics/5EAB2058-31DD-4014-8280-526FFD0C1B37.jpg",
UnitStatus: 2,
UnitHeaderDMSoundex: {
En: "ZZ E784500 ZZ ",
He: "ZZ H784500 ZZ "
},
UnitDisplayStatus: 2,
RightsCode: 1,
UnitId: 71253,
IsValueUnit: true,
StatusDesc: "Edit",
PlaceParentTypeCodeDesc: {
En: "Country"
},
PlaceParentId: 67291,
UserLexicon: null,
Attachments: [ ],
Slug: {
En: "place_bielsk",
He: "מקום_ביילסק"
},
Header: {
En: "BIELSK",
He: "ביילסק"
},
thumbnail_url: "https://storage.googleapis.com/bhs-thumbnails/5EAB2058-31DD-4014-8280-526FFD0C1B37.jpg",
ForPreview: false
}
```

**Comment by OriHoch** [comment] 2017-04-24 08:56
I'll try to reproduce it locally

**Comment by OriHoch** [comment] 2017-04-24 12:30
the problem was with logic of which items should be shown

fixed in [latest draft release](https://github.com/Beit-Hatfutsot/dbs-back/releases)

will re-run ensure_required_metadata

**Comment by OriHoch** [comment] 2017-04-24 12:40
ok, ran ensure_required_metadata on places collection - it deleted a lot of items which shouldn't have been shown
looks ok now

**Closed by OriHoch** 2017-04-24 12:40 UTC
